### ISSUE TITLE
Pypi release

### ISSUE THREAD

**Issue by chr1st1ank** [ryneeverett/mkcodes#14]
The idea of the project is quite useful. Would it be possible to create a PyPi release? With [Poetry](https://python-poetry.org/) this is fairly simple.
I'd rather add another pip package in a test pipeline instead of custom treatment for installation directly from github. Also in some environments (e.g. behind a corporate proxy) installation from github might not be possible easily.

**Comment by ryneeverett** [comment]
No problem. I've been using poetry for any python development I've done lately so I'll have to check out what it has to offer with respect to publishing.

**Comment by ryneeverett** [comment]
Wow, that was way easier than trying to remember how to use twine. Thanks for the tip!

**Comment by chr1st1ank** [comment]
That was quick :-)
Thanks
