### ISSUE TITLE
[unrelated] Gentoo gentoo-check-unstable-keywords

### ISSUE THREAD

**Issue by redjard** [ryneeverett/mkcodes#15]
Sorry to open this here, I saw no other way to reach you.  
Some time ago you had a script "gentoo-check-unstable-keywords" in your "gentoo-scripts" repo, but the repo isn't available anymore and I cannot find an archive of it.

Do you by chance still have the script? Could you provide me with a copy?

**Comment by ryneeverett** [comment]
Sorry but I can't find a copy of those scripts either. I uploaded those scripts at the request of a friend and didn't suppose anybody else used them.

I didn't have much insight into how to manage a gentoo configuration though so I don't think it's much of a loss. Best of luck!

**Comment by redjard** [comment]
Ah, that's unfortunate. I suppose I'll have to rewrite it.  
Thanks
